### ISSUE TITLE
erro instalar package

### ISSUE THREAD

**Issue by ricardorohde** [pauloalvis/Delphi-PraButtonStyle#2]
[dcc32 Error] PraButtonStyle.pas(262): E2037 Declaration of 'ChangeScale' differs from previous declaration

**Comment by pauloalvis** [comment]
Qual a versão do Delphi que vc esta instalando

**Comment by ricardorohde** [comment]
Delphi Seatle

adicionei 
PraButtonStyle\source
PraButtonStyle\source\commom
no librarypath...
e agora estou tentando instalar o package.. mas da este erro...

eu removi o override e o inherited da procedure e compilou

**Comment by pauloalvis** [comment]
Sim provavelmente essa função ainda não existia com os mesmos parâmetros na versão Seatle, estou sem essa versão para testes no momento, Mas faça os testes ai, acredito que não influenciar no funcionamento para vc.
