### ISSUE TITLE
version to lazarus?

### ISSUE THREAD

**Issue by fraurino** [pauloalvis/Delphi-PraButtonStyle#5]
version to lazarus?

**Comment by pauloalvis** [comment]
There are currently no plans to release a version for lazarus

**Comment by fraurino** [comment]
OK. I will try to make the migration, delphi to lazarus, and try to succeed, I will pass on to you as a contribution.

**Comment by pauloalvis** [comment]
will be of great importance to the community, thank you very much

**Comment by EMBBlaster** [comment]
Pull request for this issue: #8
